/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.boerenbridge.screens;

import com.mycompany.boerenbridge.AbstractPlayer;
import com.mycompany.boerenbridge.Game;
import com.mycompany.boerenbridge.RealPlayer;
import com.mycompany.boerenbridge.Round;
import java.awt.HeadlessException;
import java.util.List;
import java.util.Objects;
import java.util.Random;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.DefaultFormatter;

/**
 *
 * @author b.smeets
 */
public class AantalSlagenDialog extends javax.swing.JDialog {

    private final Round round;
    private final Game game;

    /**
     * Creates new form AantalSlagenDialog
     */
    public AantalSlagenDialog(java.awt.Frame parent, boolean modal, Round round) {
        super(parent, modal);
        this.round = round;
        this.game = Game.getSingleton();
        initComponents();
        setTitle("Ronde " + round.getRoundNumber() + ". Aantal kaarten: " + round.getNumberOfCards());
        fillSpinner();
    }
    
    private void fillSpinner() {
        SpinnerNumberModel spinnerNumberModel = new SpinnerNumberModel();
        spinnerNumberModel.setMaximum(round.getNumberOfCards());
        spinnerNumberModel.setMinimum(0);
        spinnerNumberModel.setValue(round.getNumberOfCards()/Game.NUMBER_OF_PLAYERS);
        jSpinner1.setModel(spinnerNumberModel);
        ((DefaultFormatter)((JSpinner.DefaultEditor)jSpinner1.getEditor()).getTextField().getFormatter()).setAllowsInvalid(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        okSlagenButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okSlagenButton.setText("Ok");
        okSlagenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okSlagenButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Hoeveel slagen denk je te halen?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okSlagenButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okSlagenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okSlagenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okSlagenButtonActionPerformed
        final Integer guess = Integer.valueOf(jSpinner1.getModel().getValue().toString());
        if (round.getLastPlayer().equals(game.getRealPlayer())) {
            if (round.getNotAllowedGuess() == guess ){
                JOptionPane.showMessageDialog(null, "We mogen niet precies "+ round.getNumberOfCards()+ " slagen raden. \nKies een ander aantal slagen.", "Geen valide invoer", JOptionPane.ERROR_MESSAGE);
            } else {
                performFinish(guess);
            }
        } else {
            performFinish(guess);
        }
    }//GEN-LAST:event_okSlagenButtonActionPerformed

    public void performFinish(final Integer guess) {
        this.dispose();
        round.setSlagenFor(game.getRealPlayer(), guess);
        round.getRondeScreen().addPlayerInfo(game.getRealPlayer());
        if (round.getSlagen().values().stream().noneMatch(Objects::isNull)) {
            round.determineTroef();
            if (round.getTroefCompeters().size() > 1) {
                round.getRondeScreen().setRandomTroefMakerAndNotifyUser();
            }
            if (round.getTroefMaker() instanceof RealPlayer) {
                round.getRondeScreen().createTroefChooser();
            }
        }
        if (!round.getRobotsAfterPlayer().isEmpty()) {
        	round.getRondeScreen().doRobotSlagenGuesses(round.getRobotsAfterPlayer());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton okSlagenButton;
    // End of variables declaration//GEN-END:variables
}
