/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.boerenbridge.screens;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import com.mycompany.boerenbridge.Game;

import ai.AIDifficulty;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JRadioButton;

/**
 *
 * @author b.smeets
 */
public class StartScreen extends javax.swing.JFrame {
    
    private static int counter = 0;

    private String playerName;
    List<JRadioButton> radioButtons = new ArrayList<>();

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
        initRadioButtons();
        hardButton.setSelected(true);
        nameEntryField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if (!nameEntryField.getText().isEmpty()) {
                    playButton.setEnabled(true);
                    playerName = nameEntryField.getText();
                } 
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (nameEntryField.getText().isEmpty()) {
                    playButton.setEnabled(false);
                    playerName = "";
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        nameEntryField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        easyButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        mediumButton = new javax.swing.JRadioButton();
        hardButton = new javax.swing.JRadioButton();
        harderButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Boerenbridge");
        jLabel1.setToolTipText("");

        playButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playButton.setText("Spelen");
        playButton.setEnabled(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        nameEntryField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setText("Vul je naam in:");

        easyButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        easyButton.setText("Heel makkelijk");
        easyButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                easyButtonItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setText("Moeilijkheid:");

        mediumButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mediumButton.setText("Makkelijk");
        mediumButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mediumButtonItemStateChanged(evt);
            }
        });

        hardButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hardButton.setText("Gemiddeld");
        hardButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hardButtonItemStateChanged(evt);
            }
        });

        harderButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        harderButton.setText("Moeilijk");
        harderButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                harderButtonItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(harderButton)
                    .addComponent(hardButton)
                    .addComponent(mediumButton)
                    .addComponent(easyButton)
                    .addComponent(nameEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nameEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(easyButton)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(mediumButton)
                .addGap(18, 18, 18)
                .addComponent(hardButton)
                .addGap(18, 18, 18)
                .addComponent(harderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        this.dispose();
        Game game = Game.getSingleton();
        game.createPlayer(playerName);
        game.setAIDifficulty(getDifficulty());
        game.start();
    }//GEN-LAST:event_playButtonActionPerformed

    private void easyButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_easyButtonItemStateChanged
        if (counter == 0) {
            easyButton.setSelected(true);
        }
        counter++;
        
        if (easyButton.isSelected()) {
            deselectAllExcept(easyButton);
            counter = 0;
        }
    }//GEN-LAST:event_easyButtonItemStateChanged

    private void mediumButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mediumButtonItemStateChanged
        if (counter == 0) {
            mediumButton.setSelected(true);
        }
        counter++;
        if (mediumButton.isSelected()) {
            deselectAllExcept(mediumButton);
            counter = 0;
        }
    }//GEN-LAST:event_mediumButtonItemStateChanged

    private void hardButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hardButtonItemStateChanged
        if (counter == 0) {
            hardButton.setSelected(true);
        }
        counter++;
        if (hardButton.isSelected()) {
            deselectAllExcept(hardButton);
            counter = 0;
        }
    }//GEN-LAST:event_hardButtonItemStateChanged

    private void harderButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_harderButtonItemStateChanged
        if (counter == 0){
            harderButton.setSelected(true);
        } 
        counter++;
        if (harderButton.isSelected()) {
            deselectAllExcept(harderButton);
            counter = 0;
        }
    }//GEN-LAST:event_harderButtonItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton easyButton;
    private javax.swing.JRadioButton hardButton;
    private javax.swing.JRadioButton harderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton mediumButton;
    private javax.swing.JTextField nameEntryField;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables

    private void deselectAllExcept(JRadioButton button) {
        radioButtons.stream().filter(b -> !b.equals(button)).forEach(b -> b.setSelected(false));
    }

    private void initRadioButtons() {
        this.radioButtons.add(easyButton);
        this.radioButtons.add(mediumButton);
        this.radioButtons.add(hardButton);
        this.radioButtons.add(harderButton);
    }

    private AIDifficulty getDifficulty() {
        if (easyButton.isSelected()) {
            return AIDifficulty.EASY;
        }
        if (mediumButton.isSelected()) {
            return AIDifficulty.MEDIUM;
        }
        if (hardButton.isSelected()) {
            return AIDifficulty.HARD;
        }
        if (harderButton.isSelected()) {
            return AIDifficulty.HARDER;
        }
        throw new IllegalStateException("Op de een of andere manier was er geen moeilijkheidsbutton geselecteerd");
    }
}
